import { db } from "./db";
import { listings } from "@shared/schema";
import { log } from "./index";

export async function seedDatabase() {
  const existing = await db.select().from(listings);
  if (existing.length > 0) {
    log("Database already seeded, skipping");
    return;
  }

  log("Seeding database with sample data...");

  const seedData = [
    {
      category: "nightlife",
      name: "Zen Rooftop Lounge",
      interest: "Nightlife",
      subInterest: "Rooftop Bar",
      description: "A stylish rooftop lounge with cocktails, DJs and city views.",
      location: "7 Ariapita Ave, Woodbrook, Port of Spain",
      latitude: 10.6605,
      longitude: -61.508,
      website: "https://zenrooftop.tt",
      phone: "+1 (868) 555-0123",
      email: "info@zenrooftop.tt",
      rewardPoints: 25,
      metadata: {
        openingHours: "Fri-Sat 6:00 PM - 2:00 AM",
        openingHoursNotes: "Happy hour 6-7 PM. Kitchen closes 11 PM.",
        noCoverCharge: true,
        currency: "TTD",
        coverChargeAmount: 0,
        dressCode: "Smart Casual",
        specialNights: ["Ladies night (Thu)", "2-for-1 cocktails (6-8 PM)"],
        videoUrls: ["https://youtu.be/xxxx"],
        ageRestriction: "18+",
        bookingUrl: "https://zenrooftop.tt/reserve",
        amenities: ["Bar/Lounge", "Parking", "Wheelchair Accessible"],
      },
    },
    {
      category: "nightlife",
      name: "Kaiso Blues Cafe",
      interest: "Nightlife",
      subInterest: "Live Music Venue",
      description: "Live calypso, jazz, and blues in an intimate setting with local vibes.",
      location: "Western Main Rd, St. James, Port of Spain",
      latitude: 10.6561,
      longitude: -61.5233,
      website: "https://kaisoblues.tt",
      phone: "+1 (868) 555-0145",
      email: "info@kaisoblues.tt",
      rewardPoints: 20,
      metadata: {
        openingHours: "Wed-Sun 7:00 PM - 1:00 AM",
        openingHoursNotes: "Live music starts 9 PM.",
        noCoverCharge: false,
        currency: "TTD",
        coverChargeAmount: 50,
        dressCode: "Casual",
        ageRestriction: "21+",
        bookingUrl: "https://kaisoblues.tt/reserve",
        amenities: ["Bar/Lounge", "Parking"],
        specialNights: ["Open mic (Wed)", "Jazz night (Fri)"],
      },
    },
    {
      category: "beaches",
      name: "Maracas Bay Beach",
      interest: "Nature",
      subInterest: "Beach",
      description: "Popular sandy beach with food stalls and swimming areas.",
      location: "Maracas Bay, Trinidad",
      latitude: 10.7489,
      longitude: -61.4525,
      website: "https://visittrinbago.org/beaches/maracas",
      phone: "+1 (868) 555-0188",
      email: "hello@maracasbeach.tt",
      rewardPoints: 10,
      metadata: {
        freeEntry: true,
        currency: "TTD",
        entryFeeAmount: 0,
        openingHours: "Daily 6:00 AM - 6:00 PM",
        openingHoursNotes: "Peak crowd on weekends; lifeguards 9 AM-5 PM.",
        amenities: ["Lifeguard", "Changerooms", "Food", "Wheelchair Accessible"],
      },
    },
    {
      category: "beaches",
      name: "Pigeon Point Beach",
      interest: "Nature",
      subInterest: "Beach",
      description: "Iconic white sand beach with thatched-roof jetty and crystal-clear water.",
      location: "Pigeon Point, Tobago",
      latitude: 11.1618,
      longitude: -60.8276,
      website: "https://pigeonpointtobago.tt",
      phone: "+1 (868) 555-0192",
      email: "info@pigeonpoint.tt",
      rewardPoints: 15,
      metadata: {
        freeEntry: false,
        currency: "TTD",
        entryFeeAmount: 20,
        openingHours: "Daily 7:00 AM - 6:00 PM",
        openingHoursNotes: "Entry fee includes chair rental.",
        amenities: ["Changerooms", "Food", "Snorkelling", "Parking"],
      },
    },
    {
      category: "wellness",
      name: "Serenity Spa & Wellness",
      interest: "Wellness",
      subInterest: "Spa",
      description: "Massage, facials and relaxation therapies in a calm setting.",
      location: "St. Ann's, Port of Spain",
      latitude: 10.6732,
      longitude: -61.5184,
      website: "https://serenityspa.tt",
      phone: "+1 (868) 555-0144",
      email: "bookings@serenityspa.tt",
      rewardPoints: 20,
      metadata: {
        openingHours: "Mon-Sat 9:00 AM - 6:00 PM",
        openingHoursNotes: "Appointments recommended.",
        amenities: ["Wheelchair Accessible", "Food (juice bar)"],
      },
    },
    {
      category: "festivals",
      name: "Tobago Heritage Festival",
      interest: "Culture",
      subInterest: "Festival",
      description: "Annual celebration of Tobagonian culture with music, dance and food.",
      location: "Scarborough, Tobago",
      latitude: 11.1802,
      longitude: -60.7342,
      website: "https://tobagoheritagefestival.tt",
      phone: "+1 (868) 555-0199",
      email: "info@tobagoheritagefestival.tt",
      rewardPoints: 30,
      metadata: {
        organizer: "Tobago Festivals Commission",
        bookingUrl: "https://tickets.tobagoheritagefestival.tt",
        dateTime: "2026-07-25T18:00",
        dressCode: "Casual",
      },
    },
    {
      category: "festivals",
      name: "Trinidad Carnival",
      interest: "Culture",
      subInterest: "Carnival",
      description: "The greatest show on earth! A spectacular two-day parade of color, music and dance.",
      location: "Port of Spain, Trinidad",
      latitude: 10.6596,
      longitude: -61.5086,
      website: "https://trinidadcarnival.tt",
      phone: "+1 (868) 555-0200",
      email: "info@trinidadcarnival.tt",
      rewardPoints: 50,
      metadata: {
        organizer: "National Carnival Commission",
        bookingUrl: "https://trinidadcarnival.tt/tickets",
        dateTime: "2027-02-15T06:00",
        dressCode: "Costume / Casual",
      },
    },
    {
      category: "stay",
      name: "Kapok Hotel",
      interest: "Stay",
      subInterest: "Hotel",
      description: "Comfortable city hotel with pool and on-site dining.",
      location: "16-18 Cotton Hill, Port of Spain",
      latitude: 10.6755,
      longitude: -61.5136,
      website: "https://kapokhotel.com",
      phone: "+1 (868) 555-0101",
      email: "reservations@kapokhotel.com",
      rewardPoints: 40,
      metadata: {
        typeOfAccommodation: "Hotel",
        currency: "USD",
        minPrice: 120,
        maxPrice: 280,
        priceNotes: "Rates vary by season; breakfast optional.",
        checkInTime: "14:00",
        checkOutTime: "11:00",
        amenities: ["Pool", "Restaurant", "Parking", "Free Wi-Fi", "Room Service", "Bar/Lounge"],
        bookingUrl: "https://kapokhotel.com/book",
      },
    },
    {
      category: "transport",
      name: "Island Shuttle Services",
      interest: "Transport",
      subInterest: "Shuttle",
      description: "Airport transfers and island-wide private shuttle service.",
      location: "Piarco International Airport, Trinidad",
      latitude: 10.5954,
      longitude: -61.3372,
      website: "https://islandshuttle.tt",
      phone: "+1 (868) 555-0160",
      email: "support@islandshuttle.tt",
      rewardPoints: 15,
      metadata: {
        bookingWebsite: "https://islandshuttle.tt/book",
      },
    },
    {
      category: "business",
      name: "Trinidad Conference Centre",
      interest: "Business",
      subInterest: "Conference Venue",
      description: "Meeting and event space with AV support and catering partners.",
      location: "Port of Spain, Trinidad",
      latitude: 10.66,
      longitude: -61.51,
      website: "https://tcc.tt",
      phone: "+1 (868) 555-0110",
      email: "events@tcc.tt",
      rewardPoints: 35,
      metadata: {
        typeOfFacility: "Conference Centre",
        guidesUrl: "https://tcc.tt/venue-guide",
        bookingUrl: "https://tcc.tt/book",
        specialFeatures: ["Meeting Rooms", "Wi-Fi", "Catering"],
      },
    },
    {
      category: "tours",
      name: "Northern Range Rainforest Hike",
      interest: "Adventure",
      subInterest: "Hiking Tour",
      description: "Guided hike through rainforest trails with river swim stop.",
      location: "Northern Range, Trinidad",
      latitude: 10.733,
      longitude: -61.383,
      website: "https://northernrangehikes.tt",
      phone: "+1 (868) 555-0177",
      email: "bookings@northernrangehikes.tt",
      rewardPoints: 20,
      metadata: {
        tourStartEndTime: "8:00 AM - 1:00 PM",
        avgCostPerPerson: "TTD 250",
        dressCode: "Comfortable shoes, light clothing",
        bookingWebsite: "https://northernrangehikes.tt/book",
        contactName: "Asha Joseph",
      },
    },
    {
      category: "tours",
      name: "Caroni Bird Sanctuary Tour",
      interest: "Nature",
      subInterest: "Boat Tour",
      description: "Sunset boat ride through mangrove swamps to see the Scarlet Ibis.",
      location: "Caroni Swamp, Trinidad",
      latitude: 10.5833,
      longitude: -61.45,
      website: "https://caronibirdsanctuary.tt",
      phone: "+1 (868) 555-0180",
      email: "tours@caronibirds.tt",
      rewardPoints: 25,
      metadata: {
        tourStartEndTime: "4:00 PM - 6:30 PM",
        avgCostPerPerson: "TTD 150",
        dressCode: "Casual, bring insect repellent",
        bookingWebsite: "https://caronibirdsanctuary.tt/book",
        contactName: "Marcus Williams",
      },
    },
    {
      category: "eat_drink",
      name: "The Seahorse Grill",
      interest: "Food & Drink",
      subInterest: "Seafood Restaurant",
      description: "Fresh local seafood, beachfront dining, family-friendly.",
      location: "Maracas Bay, Trinidad",
      latitude: 10.7469,
      longitude: -61.4348,
      website: "https://seahorsegrill.tt",
      phone: "+1 (868) 555-0123",
      email: "reservations@seahorsegrill.tt",
      rewardPoints: 25,
      metadata: {
        typeOfCuisine: "Caribbean / Seafood",
        priceRange: "$$ (mid-range)",
        openingHours: "Mon-Sun 11:00 AM - 10:00 PM",
        bookingUrl: "https://seahorsegrill.tt/reserve",
        amenities: ["Wi-Fi", "Parking", "Wheelchair Accessible"],
      },
    },
    {
      category: "eat_drink",
      name: "Veni Mange",
      interest: "Food & Drink",
      subInterest: "Creole Restaurant",
      description: "Award-winning Creole cuisine in a charming colonial house setting.",
      location: "Woodbrook, Port of Spain",
      latitude: 10.6588,
      longitude: -61.5167,
      website: "https://venimange.tt",
      phone: "+1 (868) 555-0134",
      email: "info@venimange.tt",
      rewardPoints: 30,
      metadata: {
        typeOfCuisine: "Creole / Caribbean",
        priceRange: "$$$ (upscale)",
        openingHours: "Mon-Fri 11:30 AM - 3:00 PM",
        bookingUrl: "https://venimange.tt/book",
        amenities: ["Parking", "Wheelchair Accessible"],
      },
    },
    {
      category: "attractions",
      name: "Asa Wright Nature Centre",
      interest: "Things to Do",
      subInterest: "Nature & Wildlife",
      description: "Guided birdwatching, trails, and mountain views.",
      location: "Arima Valley, Trinidad",
      latitude: 10.649,
      longitude: -61.2805,
      website: "https://asawright.org",
      phone: "+1 (868) 555-0188",
      email: "info@asawright.org",
      rewardPoints: 40,
      metadata: {
        freeEntry: false,
        currency: "TTD",
        entryFeeAmount: 150,
        openingHours: "Tue-Sun 8:00 AM - 4:30 PM",
        openingHoursNotes: "Last entry at 3:30 PM",
        bookingUrl: "https://asawright.org/book",
        amenities: ["Guided Tours", "Gift Shop", "Wheelchair Accessible"],
      },
    },
    {
      category: "attractions",
      name: "Fort George",
      interest: "Things to Do",
      subInterest: "Historic Site",
      description: "Historic hilltop fort with panoramic views of Port of Spain and the Gulf of Paria.",
      location: "Fort George Road, Port of Spain",
      latitude: 10.6622,
      longitude: -61.5247,
      website: "https://visittrinbago.org/attractions/fort-george",
      phone: "+1 (868) 555-0195",
      email: "info@fortgeorge.tt",
      rewardPoints: 15,
      metadata: {
        freeEntry: true,
        currency: "TTD",
        entryFeeAmount: 0,
        openingHours: "Daily 8:00 AM - 5:00 PM",
        openingHoursNotes: "Best views at sunset.",
        amenities: ["Parking", "Guided Tours"],
      },
    },
    {
      category: "shopping",
      name: "Tunapuna Market",
      interest: "Shopping",
      subInterest: "Local Market",
      description: "Fresh produce, local spices, and handmade crafts.",
      location: "Tunapuna, Trinidad",
      latitude: 10.6518,
      longitude: -61.3889,
      website: "https://tunapunamarket.tt",
      phone: "+1 (868) 555-0177",
      email: "info@tunapunamarket.tt",
      rewardPoints: 20,
      metadata: {
        typeOfFacility: "Market",
        openingHours: "Mon-Sat 6:00 AM - 6:00 PM",
        amenities: ["Parking", "Wheelchair Accessible", "Food"],
      },
    },
    {
      category: "shopping",
      name: "The Falls at West Mall",
      interest: "Shopping",
      subInterest: "Shopping Mall",
      description: "Modern shopping centre with international and local brands, dining, and entertainment.",
      location: "Westmoorings, Trinidad",
      latitude: 10.6701,
      longitude: -61.5502,
      website: "https://fallswestmall.tt",
      phone: "+1 (868) 555-0185",
      email: "info@fallswestmall.tt",
      rewardPoints: 15,
      metadata: {
        typeOfFacility: "Mall",
        openingHours: "Mon-Sat 10:00 AM - 8:00 PM, Sun 12:00 PM - 6:00 PM",
        bookingUrl: "https://fallswestmall.tt/events",
        amenities: ["Parking", "Wheelchair Accessible", "Food", "Wi-Fi"],
      },
    },
  ];

  await db.insert(listings).values(seedData);
  log("Database seeded with " + seedData.length + " listings");
}
